#+STARTUP: overview
#+PROPERTY: header-args :tangle osx-setup.sh
* Show hard drive in finder
1. While in the Finder, go to the "Finder" menu and select "Preferences".
2. From the "General" tab, place a check next to "Hard disks"
   -- this will make your hard drive visible on the Desktop.
3. From the "Sidebar" tab under "Devices" again place a check next to "Hard disks"
   -- this will put your hard drive in the sidebar of any finder window, and should also add it to "Open", "Save", and "Save As..." dialog sheets (as well as others)
* OSX

#+BEGIN_SRC sh
defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder
defaults write -g ApplePressAndHoldEnabled -bool true
defaults write com.apple.dock autohide -bool true
#+END_SRC

* Xcode command line tools

Install command line tools.

#+BEGIN_SRC sh
xcode-select --install
#+END_SRC

* Homebrew

To make homebrew work properly you need to fix ruby script permissions.

Install.

#+BEGIN_SRC sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
#+END_SRC

Update.

#+BEGIN_SRC sh
brew update
#+END_SRC

Disable analytics.

#+BEGIN_SRC sh
brew analytics off
#+END_SRC

* Git

Install latest version of git.

#+BEGIN_SRC sh
brew install git
#+END_SRC

Set identity.

#+BEGIN_SRC sh
git config --global user.name "andersmurphy"
git config --global user.email "andersmurphy@gmail.com"
#+END_SRC

Set [[https://help.github.com/en/articles/caching-your-github-password-in-git][credential store]].

#+BEGIN_SRC sh
git config --global credential.helper osxkeychain
#+END_SRC

Set editor.

#+BEGIN_SRC  sh
git config --global core.editor 'emacsclient'
#+END_SRC

Set pull with rebase to be default.
#+BEGIN_SRC sh
git config --global pull.rebase true
#+END_SRC

Set colour ui.

#+BEGIN_SRC sh
git config --global color.ui true
#+END_SRC

Create global git ignore file.

#+BEGIN_SRC sh
rm ~/.gitignore
ln -s ~/.emacs.d/setup/dotfiles/.gitignore ~/.gitignore
#+END_SRC

Set as global ignore file.

#+BEGIN_SRC sh
git config --global core.excludesfile '~/.gitignore'
#+END_SRC

Set external git diff algorithm.

#+BEGIN_SRC sh
git config --global diff.algorithm histogram
#+END_SRC

* Emacs

Homebrew Emacs.app launches using a ruby script. As a result, MacOS Catalina uses the permissions set for ruby, not the permissions for Emacs.app.

1. Open General Settings -> Security & Privacy -> Privacy
2. select Full Disk Access in the left pane
3. click + and add /usr/bin/ruby

/usr is hidden by default on MacOS but you can toggle visibility in Finder by using Shift+Command+Period

#+BEGIN_SRC sh
brew tap daviderestivo/emacs-head
brew install emacs-head@28 --with-cocoa --with-imagemagick --with-xwidgets
#+END_SRC

Clone private sync repo.

#+BEGIN_SRC
git clone https://github.com/andersmurphy/emacs-sync.git .emacs.d/emacs-sync
#+END_SRC

** Emacs External Dependencies

Spellcheck depends on aspell.

#+BEGIN_SRC sh
brew install aspell
#+END_SRC

Emms depends on mpv to play music.

#+BEGIN_SRC sh
brew install mpv
rm ~/.config/mpv/mpv.conf
ln -s ~/.emacs.d/setup/dotfiles/.mpv/mpv.conf ~/.config/mpv/
#+END_SRC

Markdown mode depends on multimarkdown to preview markdown.

#+BEGIN_SRC sh
brew install multimarkdown
#+END_SRC

* Open jdk

Installs open jdk.

#+BEGIN_SRC sh
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk11
#+END_SRC

* Chormium

Install Chromium

#+BEGIN_SRC sh
brew install --cask chromium
open -a "Chromium" --args --make-default-browser
#+END_SRC

* Clojure

Language.

#+BEGIN_SRC sh
brew install clojure
rm ~/.clojure/deps.edn
ln -s ~/.emacs.d/setup/dotfiles/.clojure/deps.edn ~/.clojure/
#+END_SRC

Build tool.

#+BEGIN_SRC sh
brew install leiningen
rm ~/.lein/profiles.clj
ln -s ~/.emacs.d/setup/dotfiles/.lein/profiles.clj ~/.lein/
#+END_SRC

Formatter.

#+BEGIN_SRC sh
brew install --build-from-source ~/.emacs.d/setup/brew-formulae/clj-zprint.rb
#+END_SRC

LSP.

#+BEGIN_SRC sh
brew install clojure-lsp/brew/clojure-lsp-native
#+END_SRC

* Javascript

Language.

#+BEGIN_SRC sh
brew install node
#+END_SRC

Yarn.

#+BEGIN_SRC sh
npm install -g yarn
#+END_SRC

LSP.

#+BEGIN_SRC sh
npm i -g typescript-language-server; npm i -g typescript
#+END_SRC

* Html

LSP.

#+BEGIN_SRC sh
npm install -g vscode-html-languageserver-bin
#+END_SRC
* OSX Clear fonts on retina screens
- First, turn OFF “Font smoothing” in System Preferences → General
- Go to System Preferences → Displays, uncheck Default and select scaled 2× resolution
https://tonsky.me/blog/monitors/
