#+STARTUP: overview
#+PROPERTY: header-args :tangle osx-setup.sh
* OSX

#+BEGIN_SRC sh
defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder
defaults write -g ApplePressAndHoldEnabled -bool true
defaults write com.apple.dock autohide -bool true
#+END_SRC

* Xcode command line tools

Install command line tools.

We reset the path to prevent:

xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not existo

Which seems to happen if you are installing a new version of xcode.

#+BEGIN_SRC sho
xcode-select --install
wait
sudo xcode-select --reset 
#+END_SRC

* Homebrew

To make homebrew work properly you need to fix ruby script permissions.

Install.

#+BEGIN_SRC sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
wait
#+END_SRC

Update.

#+BEGIN_SRC sh
brew update
wait
#+END_SRC

Disable analytics.

#+BEGIN_SRC sh
brew analytics off
brew tap homebrew/cask
#+END_SRC

* Git

Install latest version of git.

#+BEGIN_SRC sh
brew install git
wait
#+END_SRC

Set identity.

#+BEGIN_SRC sh
git config --global user.name "andersmurphy"
git config --global user.email "andersmurphy@gmail.com"
#+END_SRC

Set encrypted diffs.

#+BEGIN_SRC sh
git config --global diff.gpg.textconv "gpg --no-tty --decrypt"
#+END_SRC

Set editor. I always use magit so nano is only in case
of emergencies (emacs down).

#+BEGIN_SRC  sh
git config --global core.editor 'nano'
#+END_SRC

Set pull with rebase to be default.
#+BEGIN_SRC sh
git config --global pull.rebase true
#+END_SRC

Prune local branches when fetching changes from remote.
#+BEGIN_SRC sh
git config --global fetch.prune true
#+END_SRC

Set colour ui.

#+BEGIN_SRC sh
git config --global color.ui true
#+END_SRC

Create global git ignore file.

#+BEGIN_SRC sh
rm ~/.gitignore
ln -s ~/.emacs.d/setup/dotfiles/.gitignore ~/.gitignore
#+END_SRC

Set as global ignore file.

#+BEGIN_SRC sh
git config --global core.excludesfile '~/.gitignore'
#+END_SRC

Set external git diff algorithm.

#+BEGIN_SRC sh
git config --global diff.algorithm histogram
#+END_SRC

* Emacs

Install emacs.

#+BEGIN_SRC sh
brew install emacs --cask
wait
#+END_SRC

** Emacs External Dependencies

Spellcheck depends on aspell.

#+BEGIN_SRC sh
brew install aspell
wait
#+END_SRC

Emms depends on mpv to play music.

#+BEGIN_SRC sh
brew install mpv
wait
rm ~/.config/mpv/mpv.conf
ln -s ~/.emacs.d/setup/dotfiles/.mpv/mpv.conf ~/.config/mpv/
#+END_SRC

Jet conversion between json and edn.

#+BEGIN_SRC sh
brew install borkdude/brew/jet
wait
#+END_SRC

gnupg (gpg) for encryption (pinned to version 2.40). As later versions currently break emacs (M-x view-emacs-problems). 

#+BEGIN_SRC sh
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/59edfe598541186430d49cc34f42671e849e2fc9/Formula/gnupg.rb > gnupg.rb
wait
brew install gnupg.rb
wait
rm gnupg.rb 
#+END_SRC

ripgrep needed for things that use ripgrep (eg: magit-todo) as OSX doesn't ship with grep.

#+BEGIN_SRC sh
brew install ripgrep
#+END_SRC

* Open jdk

Installs open jdk.

#+BEGIN_SRC sh
brew tap AdoptOpenJDK/openjdk
brew install adoptopenjdk17
wait
#+END_SRC

* Clojure

Language.

#+BEGIN_SRC sh
brew install clojure
wait
rm ~/.clojure/deps.edn
rm ~/.clojure/user.cljc
ln -s ~/.emacs.d/setup/dotfiles/.clojure/deps.edn ~/.clojure/
ln -s ~/.emacs.d/setup/dotfiles/.clojure/user.cljc ~/.clojure/
#+END_SRC

Build tool.

#+BEGIN_SRC sh
brew install leiningen
wait
rm ~/.lein/profiles.clj
ln -s ~/.emacs.d/setup/dotfiles/.lein/profiles.clj ~/.lein/
#+END_SRC

LSP.

#+BEGIN_SRC sh
brew install clojure-lsp/brew/clojure-lsp-native
#+END_SRC

clj-kondo config (used by LSP).

#+BEGIN_SRC sh
rm -r ~/.clj-kondo
mkdir ~/.clj-kondo
ln -s ~/.emacs.d/setup/dotfiles/.clj-kondo/config.edn ~/.clj-kondo/
#+END_SRC

* Babashka

Language.

#+BEGIN_SRC sh
brew install borkdude/brew/babashka
#+END_SRC

* Fennel

Language.

#+BEGIN_SRC sh
brew install fennel
#+END_SRC

* OSX misc
** Clear fonts on retina screens
- First, turn OFF “Font smoothing” in System Preferences → General
- Go to System Preferences → Displays, uncheck Default and select scaled 2× resolution
https://tonsky.me/blog/monitors/

** Show hard drive in finder
1. While in the Finder, go to the "Finder" menu and select "Preferences".
2. From the "General" tab, place a check next to "Hard disks"
   -- this will make your hard drive visible on the Desktop.
3. From the "Sidebar" tab under "Devices" again place a check next to "Hard disks"
   -- this will put your hard drive in the sidebar of any finder window, and should also add it to "Open", "Save", and "Save As..." dialog sheets (as well as others)

** /Usr

/usr is hidden by default on MacOS but you can toggle visibility in Finder by using Shift+Command+Period
